version: '3.8'

services:
  app:
    image: eclipse-temurin:8-jre
    container_name: transdep-eticket-api-sample
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - postgres
    volumes:
      - ./target/transdep-eticket-api-sample.war:/app/transdep-eticket-api-sample.war:ro
      - ./logs:/app/logs
    working_dir:
      TZ: Asia/Ulaanbaatar
    command: java -Xms256m -Xmx512m -jar transdep-eticket-api-sample.war --spring.profiles.active=test
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - transdep-net


networks:
  transdep-net:
    driver: bridge
